from django.core.management.base import BaseCommand

# ARNs must match those generated by tests/fixtures/generate_fixtures.py
# ri_id = f"ri-{abs(hash(itype+region)):016x}"[:22]

# Counts derived from generate_fixtures.py P25 sizing (50× base_count, daily growth)
RI_FIXTURES = [
    {
        "reservation_id":  "ri-7e83e8e3b807a0bb",
        "reservation_arn": "arn:aws:ec2:us-east-1:123456789012:reserved-instances/ri-7e83e8e3b807a0bb",
        "instance_type": "m5.xlarge", "instance_family": "m5",
        "normalized_units": 7096.0, "region": "us-east-1",  # 887 × 8
        "tenancy": "default", "platform": "Linux/UNIX",
        "offering_class": "standard", "offering_type": "No Upfront",
        "instance_count": 887, "start_date": "2025-01-01", "end_date": "2028-01-01",
        "fixed_price": 0.0, "recurring_hourly_cost": 0.1344,
        "scope": "Region", "state": "active",
    },
    {
        "reservation_id":  "ri-335bbbf2ab3029db",
        "reservation_arn": "arn:aws:ec2:us-east-1:123456789012:reserved-instances/ri-335bbbf2ab3029db",
        "instance_type": "c5.xlarge", "instance_family": "c5",
        "normalized_units": 7000.0, "region": "us-east-1",  # 875 × 8
        "tenancy": "default", "platform": "Linux/UNIX",
        "offering_class": "convertible", "offering_type": "No Upfront",
        "instance_count": 875, "start_date": "2025-01-01", "end_date": "2028-01-01",
        "fixed_price": 0.0, "recurring_hourly_cost": 0.1156,
        "scope": "Region", "state": "active",
    },
    {
        "reservation_id":  "ri-6980e5dd8d98c2f2",
        "reservation_arn": "arn:aws:ec2:us-east-1:123456789012:reserved-instances/ri-6980e5dd8d98c2f2",
        "instance_type": "r5.2xlarge", "instance_family": "r5",
        "normalized_units": 22208.0, "region": "us-east-1",  # 1388 × 16
        "tenancy": "default", "platform": "Linux/UNIX",
        "offering_class": "standard", "offering_type": "No Upfront",
        "instance_count": 1388, "start_date": "2025-02-01", "end_date": "2028-02-01",
        "fixed_price": 0.0, "recurring_hourly_cost": 0.3276,
        "scope": "Region", "state": "active",
    },
    {
        "reservation_id":  "ri-5170b50737046ed9",
        "reservation_arn": "arn:aws:ec2:us-west-2:123456789012:reserved-instances/ri-5170b50737046ed9",
        "instance_type": "m5.2xlarge", "instance_family": "m5",
        "normalized_units": 7264.0, "region": "us-west-2",  # 454 × 16
        "tenancy": "default", "platform": "Linux/UNIX",
        "offering_class": "convertible", "offering_type": "No Upfront",
        "instance_count": 454, "start_date": "2025-01-01", "end_date": "2028-01-01",
        "fixed_price": 0.0, "recurring_hourly_cost": 0.2995,
        "scope": "Region", "state": "active",
    },
]

SP_FIXTURES = [
    {
        "savings_plan_id":  "sp-abc123def456",
        "savings_plan_arn": "arn:aws:savingsplans::123456789012:savingsplan/sp-abc123def456",
        "plan_type":        "ComputeSavingsPlan",
        "commitment_hourly": 116.7486,
        "start_date": "2025-01-01", "end_date": "2026-01-01",
        "state": "active",
    },
]


class Command(BaseCommand):
    help = "Seed ReservedInstance and SavingsPlan records from fixture data"

    def handle(self, *args, **options):
        from apps.accounts.models import AwsAccount
        from apps.reservations.models import ReservedInstance, SavingsPlan

        try:
            account = AwsAccount.objects.get(account_id="123456789012")
        except AwsAccount.DoesNotExist:
            account = AwsAccount.objects.create(
                account_id="123456789012",
                account_name="acme-prod",
                is_payer=True,
            )

        for ri in RI_FIXTURES:
            ReservedInstance.objects.update_or_create(
                reservation_id=ri["reservation_id"],
                defaults={"account": account, **{k: v for k, v in ri.items() if k != "reservation_id"}},
            )
        self.stdout.write(f"Seeded {len(RI_FIXTURES)} reserved instances")

        for sp in SP_FIXTURES:
            SavingsPlan.objects.update_or_create(
                savings_plan_id=sp["savings_plan_id"],
                defaults={"account": account, **{k: v for k, v in sp.items() if k != "savings_plan_id"}},
            )
        self.stdout.write(f"Seeded {len(SP_FIXTURES)} savings plans")
        self.stdout.write(self.style.SUCCESS("Done"))
