# Generated by Django 5.1.15 on 2026-03-16 01:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EtlRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rows_read', models.BigIntegerField(default=0)),
                ('rows_after_dedup', models.BigIntegerField(default=0)),
                ('rows_loaded', models.BigIntegerField(default=0)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_detail', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('running', 'running'), ('success', 'success'), ('failed', 'failed')], default='pending', max_length=16)),
                ('cur_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etl_runs', to='ingestion.curfile')),
            ],
        ),
    ]
