# Generated by Django 5.1.15 on 2026-03-16 01:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservedInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_id', models.CharField(max_length=64, unique=True)),
                ('reservation_arn', models.CharField(max_length=512, unique=True)),
                ('instance_type', models.CharField(db_index=True, max_length=64)),
                ('instance_family', models.CharField(max_length=64)),
                ('normalized_units', models.FloatField()),
                ('region', models.CharField(max_length=64)),
                ('tenancy', models.CharField(max_length=32)),
                ('platform', models.CharField(max_length=64)),
                ('offering_class', models.CharField(max_length=32)),
                ('offering_type', models.CharField(max_length=64)),
                ('instance_count', models.IntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('fixed_price', models.DecimalField(decimal_places=6, max_digits=20)),
                ('recurring_hourly_cost', models.DecimalField(decimal_places=6, max_digits=20)),
                ('scope', models.CharField(max_length=32)),
                ('state', models.CharField(max_length=32)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reserved_instances', to='accounts.awsaccount')),
            ],
        ),
        migrations.CreateModel(
            name='RiRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('recommendation_type', models.CharField(max_length=32)),
                ('instance_type', models.CharField(max_length=64)),
                ('region', models.CharField(max_length=64)),
                ('platform', models.CharField(blank=True, max_length=64)),
                ('quantity', models.IntegerField()),
                ('estimated_monthly_savings', models.DecimalField(decimal_places=2, max_digits=20)),
                ('break_even_months', models.FloatField(blank=True, null=True)),
                ('analysis_window_days', models.IntegerField(default=30)),
                ('confidence_score', models.FloatField()),
                ('detail_json', models.JSONField(default=dict)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.awsaccount')),
            ],
        ),
        migrations.CreateModel(
            name='SavingsPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('savings_plan_id', models.CharField(max_length=64, unique=True)),
                ('savings_plan_arn', models.CharField(max_length=512)),
                ('plan_type', models.CharField(max_length=32)),
                ('commitment_hourly', models.DecimalField(decimal_places=6, max_digits=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('state', models.CharField(max_length=32)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='savings_plans', to='accounts.awsaccount')),
            ],
        ),
    ]
