# Generated by Django 5.1.15 on 2026-03-16 01:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AwsAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.CharField(max_length=12, unique=True)),
                ('account_name', models.CharField(max_length=128)),
                ('iam_role_arn', models.CharField(blank=True, max_length=256)),
                ('is_payer', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['account_id'],
            },
        ),
        migrations.CreateModel(
            name='CurManifest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s3_bucket', models.CharField(max_length=256)),
                ('s3_prefix', models.CharField(max_length=512)),
                ('report_name', models.CharField(max_length=256)),
                ('time_unit', models.CharField(choices=[('HOURLY', 'HOURLY'), ('DAILY', 'DAILY')], max_length=10)),
                ('compression', models.CharField(choices=[('GZIP', 'GZIP'), ('Parquet', 'Parquet')], max_length=10)),
                ('aws_region', models.CharField(max_length=32)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manifests', to='accounts.awsaccount')),
            ],
        ),
    ]
