# Generated by Django 5.1.15 on 2026-03-16 01:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForecastRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grain', models.CharField(max_length=16)),
                ('service', models.CharField(blank=True, max_length=128)),
                ('region', models.CharField(blank=True, max_length=64)),
                ('usage_type', models.CharField(blank=True, max_length=256)),
                ('training_start', models.DateField()),
                ('training_end', models.DateField()),
                ('forecast_horizon', models.IntegerField()),
                ('model_name', models.CharField(default='chronos-t5-small', max_length=64)),
                ('mae', models.FloatField(blank=True, null=True)),
                ('mape', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.awsaccount')),
            ],
        ),
        migrations.CreateModel(
            name='ForecastPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('predicted_cost', models.DecimalField(decimal_places=6, max_digits=20)),
                ('lower_bound', models.DecimalField(decimal_places=6, max_digits=20)),
                ('upper_bound', models.DecimalField(decimal_places=6, max_digits=20)),
                ('actual_cost', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('forecast_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='forecasting.forecastrun')),
            ],
            options={
                'unique_together': {('forecast_run', 'timestamp')},
            },
        ),
    ]
