# Generated by Django 5.1.15 on 2026-03-16 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecasting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='forecastrun',
            name='grouping_level',
            field=models.CharField(choices=[('region', 'Region'), ('region_service', 'Region + Service'), ('region_service_instance', 'Region + Service + Instance Type')], default='region_service', max_length=32),
        ),
        migrations.AddField(
            model_name='forecastrun',
            name='instance_type',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
