# Generated by Django 5.1.15 on 2026-03-16 01:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurDownloadJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_period', models.CharField(max_length=20)),
                ('s3_keys', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('running', 'running'), ('success', 'success'), ('failed', 'failed')], default='pending', max_length=10)),
                ('celery_task_id', models.CharField(blank=True, max_length=64)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('rows_downloaded', models.BigIntegerField(default=0)),
                ('manifest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='accounts.curmanifest')),
            ],
        ),
        migrations.CreateModel(
            name='CurFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s3_key', models.CharField(max_length=1024)),
                ('local_path', models.CharField(max_length=1024)),
                ('file_hash_sha256', models.CharField(max_length=64)),
                ('size_bytes', models.BigIntegerField()),
                ('downloaded_at', models.DateTimeField(auto_now_add=True)),
                ('etl_status', models.CharField(choices=[('pending', 'pending'), ('processed', 'processed'), ('error', 'error')], default='pending', max_length=10)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='ingestion.curdownloadjob')),
            ],
        ),
    ]
