# Generated by Django 5.1.15 on 2026-03-16 01:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SplittingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('service', models.CharField(max_length=128)),
                ('region', models.CharField(max_length=64)),
                ('split_by_tag_key', models.CharField(max_length=128)),
                ('weight_strategy', models.CharField(choices=[('equal', 'equal'), ('proportional_usage', 'proportional_usage'), ('custom_weight', 'custom_weight')], max_length=32)),
                ('custom_weights', models.JSONField(default=dict)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SplitResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_period', models.CharField(db_index=True, max_length=20)),
                ('hour', models.DateTimeField(db_index=True)),
                ('region', models.CharField(db_index=True, max_length=64)),
                ('usage_type', models.CharField(db_index=True, max_length=256)),
                ('tenant_tag_value', models.CharField(db_index=True, max_length=256)),
                ('original_cost', models.DecimalField(decimal_places=10, max_digits=20)),
                ('allocated_cost', models.DecimalField(decimal_places=10, max_digits=20)),
                ('allocation_weight', models.DecimalField(decimal_places=8, max_digits=10)),
                ('splitting_rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='splitting.splittingrule')),
            ],
            options={
                'unique_together': {('splitting_rule', 'hour', 'region', 'usage_type', 'tenant_tag_value')},
            },
        ),
    ]
