# Generated by Django 5.1.15 on 2026-03-16 01:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnomalyDetectionRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grain', models.CharField(max_length=16)),
                ('method', models.CharField(max_length=32)),
                ('window_hours', models.IntegerField()),
                ('sigma_threshold', models.FloatField(default=3.5)),
                ('min_cost_delta', models.DecimalField(decimal_places=2, default=5.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.awsaccount')),
            ],
        ),
        migrations.CreateModel(
            name='CostAnomaly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(db_index=True, max_length=128)),
                ('region', models.CharField(max_length=64)),
                ('usage_type', models.CharField(max_length=256)),
                ('linked_account_id', models.CharField(max_length=12)),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('direction', models.CharField(choices=[('spike', 'spike'), ('drop', 'drop')], max_length=8)),
                ('baseline_cost', models.DecimalField(decimal_places=6, max_digits=20)),
                ('observed_cost', models.DecimalField(decimal_places=6, max_digits=20)),
                ('pct_change', models.FloatField()),
                ('z_score', models.FloatField(blank=True, null=True)),
                ('chronos_sigma', models.FloatField(blank=True, null=True)),
                ('detected_by', models.CharField(default='ensemble', max_length=32)),
                ('acknowledged', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('detection_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anomalies', to='anomalies.anomalydetectionrun')),
            ],
        ),
    ]
